# Generated by Django 5.1.7 on 2026-06-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avaliação de Procedimento',
                'verbose_name_plural': 'Avaliações de Procedimento',
            },
        ),
        migrations.CreateModel(
            name='FotoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='procedimento/fotos/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('momento', models.CharField(choices=[('antes', 'Antes'), ('durante', 'Durante'), ('depois', 'Depois')], max_length=20)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Procedimento',
                'verbose_name_plural': 'Fotos de Procedimento',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField()),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('observacoes_profissional', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tempo_estimado', models.IntegerField(default=60, help_text='Tempo estimado em minutos')),
                ('tempo_real', models.IntegerField(blank=True, help_text='Tempo real em minutos', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['-data_agendamento'],
            },
        ),
        migrations.CreateModel(
            name='ServicoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_estimado', models.IntegerField(help_text='Tempo estimado em minutos')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviço de Procedimento',
                'verbose_name_plural': 'Serviços de Procedimento',
            },
        ),
    ]
