# Generated by Django 5.1.7 on 2025-08-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0003_agendamentovacina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoEstetismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_estimado', models.IntegerField(help_text='Tempo estimado em minutos')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviço de Estetismo',
                'verbose_name_plural': 'Serviços de Estetismo',
            },
        ),
        migrations.CreateModel(
            name='BanhoTosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField()),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('observacoes_profissional', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tempo_estimado', models.IntegerField(default=60, help_text='Tempo estimado em minutos')),
                ('tempo_real', models.IntegerField(blank=True, help_text='Tempo real em minutos', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banho_tosas', to='pets.pet')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banho_tosas_realizados', to=settings.AUTH_USER_MODEL)),
                ('servicos', models.ManyToManyField(related_name='banho_tosas', to='banho_tosa.servicoestetismo')),
            ],
            options={
                'verbose_name': 'Banho e Tosa',
                'verbose_name_plural': 'Banho e Tosa',
                'ordering': ['-data_agendamento'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoBanhoTosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('banho_tosa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='banho_tosa.banhotosa')),
            ],
            options={
                'verbose_name': 'Avaliação de Banho e Tosa',
                'verbose_name_plural': 'Avaliações de Banho e Tosa',
            },
        ),
        migrations.CreateModel(
            name='FotoBanhoTosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='banho_tosa/fotos/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('momento', models.CharField(choices=[('antes', 'Antes'), ('durante', 'Durante'), ('depois', 'Depois')], max_length=20)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('banho_tosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='banho_tosa.banhotosa')),
            ],
            options={
                'verbose_name': 'Foto de Banho e Tosa',
                'verbose_name_plural': 'Fotos de Banho e Tosa',
            },
        ),
    ]
