# Generated by Django 5.1.7 on 2026-06-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banho_tosa', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='pets.paciente'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotoprocedimento',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='banho_tosa.procedimento'),
        ),
        migrations.AddField(
            model_name='avaliacaoprocedimento',
            name='procedimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='banho_tosa.procedimento'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='servicos',
            field=models.ManyToManyField(related_name='procedimentos', to='banho_tosa.servicoprocedimento'),
        ),
    ]
