# docker-compose.yml
services:
  frontend:
    container_name: medihub_frontend
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-next:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_MEDIA_URL=http://backend:8000/media/
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    restart: unless-stopped
    networks:
      - medihub_network
    depends_on:
      - backend

  backend:
    container_name: medihub_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    env_file:
      - ./backend/.env
    environment:
      - ENV=development
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=medihub_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dU2q4Lpm12
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@medihub.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - medihub_network
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]

  db:
    image: postgres:17-alpine
    container_name: medihub_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: medihub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dU2q4Lpm12
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - medihub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

networks:
  medihub_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  backend_media:
    driver: local
