# Generated by Django 5.1.7 on 2026-06-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('periodo_reforco_meses', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/')),
                ('observacoes', models.TextField(blank=True)),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.convenio')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.plano')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='pets.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='VacinaAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('data_proximo_reforco', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='pets.paciente')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.vacina')),
            ],
            options={
                'verbose_name_plural': 'Vacinas Aplicadas',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('aplicado', 'Aplicado'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='agendado', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_aplicacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_vacina', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_vacina', to='pets.paciente')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.vacina')),
                ('vacina_aplicada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.vacinaaplicada')),
            ],
            options={
                'verbose_name': 'Agendamento de Vacina',
                'verbose_name_plural': 'Agendamentos de Vacinas',
                'ordering': ['-data_agendamento'],
            },
        ),
    ]
