# Generated by Django 5.1.7 on 2025-08-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='endereco',
            field=models.TextField(blank=True),
        ),
    ]
