# Generated by Django 5.1.7 on 2025-08-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_tutor_endereco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('aplicado', 'Aplicado'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='agendado', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_aplicacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_vacina', to='pets.pet')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.vacina')),
                ('vacina_aplicada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.vacinaaplicada')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_vacina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento de Vacina',
                'verbose_name_plural': 'Agendamentos de Vacinas',
                'ordering': ['-data_agendamento'],
            },
        ),
    ]
