# Generated by Django 5.1.7 on 2026-06-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=50)),
                ('via_administracao', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Item da Receita',
                'verbose_name_plural': 'Itens da Receita',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('principio_ativo', models.CharField(blank=True, max_length=100)),
                ('concentracao', models.CharField(blank=True, max_length=50)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=50)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='ControleReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_administracao', models.DateTimeField()),
                ('administrado_por', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('item_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='receitas.itemreceita')),
            ],
            options={
                'verbose_name': 'Controle de Receita',
                'verbose_name_plural': 'Controles de Receitas',
                'ordering': ['-data_administracao'],
            },
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.medicamento'),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescricao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField()),
                ('diagnostico', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='ativa', max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_prescritas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='pets.paciente')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_prescricao'],
            },
        ),
        migrations.AddField(
            model_name='itemreceita',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='receitas.receita'),
        ),
    ]
