# Generated by Django 5.1.7 on 2026-06-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_alta', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('cirurgia', 'Cirurgia'), ('tratamento', 'Tratamento'), ('observacao', 'Observação'), ('emergencia', 'Emergência'), ('pos_operatorio', 'Pós-operatório'), ('outros', 'Outros')], max_length=20)),
                ('diagnostico', models.TextField()),
                ('observacoes_entrada', models.TextField(blank=True)),
                ('observacoes_alta', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('internado', 'Internado'), ('alta', 'Alta'), ('transferido', 'Transferido'), ('obito', 'Óbito')], default='internado', max_length=20)),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('medico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes_responsavel', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='pets.paciente')),
            ],
            options={
                'verbose_name': 'Internação',
                'verbose_name_plural': 'Internações',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='EvolucoesInternacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('evolucao', models.TextField()),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='internacao.internacao')),
            ],
            options={
                'verbose_name': 'Evolução de Internação',
                'verbose_name_plural': 'Evoluções de Internação',
                'ordering': ['-data_hora'],
            },
        ),
    ]
