# Generated by Django 5.1.7 on 2026-06-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_resultado', models.IntegerField(help_text='Tempo para resultado em horas')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Exame',
                'verbose_name_plural': 'Tipos de Exames',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_coleta', models.DateTimeField(blank=True, null=True)),
                ('data_resultado', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('coletado', 'Coletado'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('observacoes_solicitacao', models.TextField(blank=True)),
                ('resultado', models.TextField(blank=True)),
                ('observacoes_resultado', models.TextField(blank=True)),
                ('arquivo_resultado', models.FileField(blank=True, null=True, upload_to='exames/resultados/')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_solicitados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='pets.paciente')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exames.tipoexame')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ParametroExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('valor_referencia', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='exames.exame')),
            ],
            options={
                'verbose_name': 'Parâmetro de Exame',
                'verbose_name_plural': 'Parâmetros de Exames',
            },
        ),
    ]
